### ISSUE TITLE
Include migration in lookout binary

### ISSUE THREAD

**Issue by smacker** [src-d/lookout#100]
We want to have a single binary as a release artifact. It means migrations must be included in it. It also makes sense to expose some of kallax migration commands through lookout.

- use go-bindata to include sql files with migration into the binary
- expose `migrate` command that would do the same as `kallax migrate up` (maybe with `--all` by default) but with migrations from go-bindata.
- update makefile and travis to use new command
- update documentation & docker-compose to run migration on start

**Comment by smola** [comment]
@smacker We probably do not need the run migration on start flag.

At least for our Kubernetes deployment, we can just use a init container running the migration, which runs before the main container starts, this way we have finer-grained control of the lifecycle.

**Comment by smacker** [comment]
Yes. We definitely shouldn't use this flag for real deployment.
We don't want the service being down while migration is running or multiple containers starting migration at the same time. :-D
But it might be handy when you run it locally. Though as I mentioned `lookout migrate && lookout serve` is simple enough. Description updated.
