### ISSUE TITLE
Better testing for server

### ISSUE THREAD

**Issue by smacker** [src-d/lookout#103]
Currently, we have small `make test-json` test which definitely isn't enough.

Proposal:

Core tests. They make sure the core of our service works correctly and we don't rely on github too heavily (means everything works with json provider):

1. Rework current `make test-json` using the same (or even improved) approach as we do with `make test-sdk`
2. Use new DB for each run, remove it after the test is finished
3. Add tests for:
  - wrong CommitRevision
  - multiple analyzers
  - tests for push event
  - test for analyzer response with error
  - local `.lookout.yml` (as a bonus because it would require separate repository and it might be too much for this task)

We also need better tests for github provider (both unit&integration) but it will be covered in another issue.

**Comment by bzz** [comment]
> We also need better tests for github provider (both unit&integration) but it will be covered in another issue.

#122

**Comment by smacker** [comment]
all except the last point. It requires special repo. I have created separate issue for that #134
