### ISSUE TITLE
Use src-d logger for grpc or remove grpc logging completely

### ISSUE THREAD

**Issue by smacker** [src-d/lookout#11]
If we want to have logs for grpc it's better to use our own logger to produce logs in the same format.
Another option is to just remove grpc logging.

If we want to go with the first option here is a proposal:

The interface of `gopkg.in/src-d/go-log.v1` is much different from `grpclog.LoggerV2` but the logrus one is almost the same.

I would propose to set default logrus logger as grpc logger (something like this):

```go
package grpclogrus

import (
	"github.com/sirupsen/logrus"
	"google.golang.org/grpc/grpclog"
)

// GrpcLogrus implements grpclog.LoggerV2 interface using logrus logger
type GrpcLogrus struct {
	*logrus.Logger
}

// V reports whether verbosity level l is at least the requested verbose level.
func (lw GrpcLogrus) V(l int) bool {
	// logrus & grpc levels are inverted
	logrusLevel := 4 - l
	return int(lw.Logger.Level) <= logrusLevel
}

func init() {
	l := GrpcLogrus{logrus.StandardLogger()}
	grpclog.SetLoggerV2(l)
}
```

And then configure it using [LoggerFactory.ApplyToLogrus](https://godoc.org/gopkg.in/src-d/go-log.v1#LoggerFactory.ApplyToLogrus)

Thoughts?

/cc @smola @bzz

**Comment by smola** [comment]
Looks good to me. Also, once it is working, you could open an issue in go-log to propose adding that logger to go-log. Maybe a subpackage without actual grpc dependency, but with the logger complying with that interface.

**Comment by smacker** [comment]
The code from above works completely fine in my branch. If @bzz and @carlosms agree, I'll create PR in this repo and after merge create a proposal for go-log.

**Comment by bzz** [comment]
As far as I can see, the proposal is motivated by 2 things:
 - necessity to have gRPC logs
 - will to have an output format, compatible with our existing go-log

Proposal sounds reasonable to me.

But before going forward, would you please clarify a bit why existing middleware-based logging solution for grpc \w logrus from https://github.com/grpc-ecosystem/go-grpc-middleware/tree/master/logging/logrus would not be a good fit?

**Comment by smacker** [comment]
That is a different kind of logging.

Setting `grpclog.SetLoggerV2` allows to get logs from grpc itself. Example of the logs on INFO level:

```
ccResolverWrapper: sending new addresses to cc: [{localhost:10301 0  <nil>}]
ClientConn switching balancer to "pick_first"
pickfirstBalancer: HandleSubConnStateChange: 0xc4201aba20, CONNECTING
pickfirstBalancer: HandleSubConnStateChange: 0xc4201aba20, READY
```

There are must be some useful messages in case of errors.


The middleware, on the other hand, works on a higher level. It intercepts methods calls, logs payload and duration.

Most probably we wouldn't need logs provided by `grpclog` in a production environment, at least if everything works normally. With the solution from above if we replace `init` by normal function call only for some ENV or verbose log level we can disable it.

Another approach as I mentioned in the issue remove this logging completely.

**Comment by carlosms** [comment]
Sounds good to me.

**Comment by bzz** [comment]
> The middleware, on the other hand, works on a higher level. It intercepts methods calls, logs payload and duration.

true, that is why it was mentioned as `middleware-based logging` :)  

My question was more like, are there any specific cases where you think that would not be enough? It should fit for case the @smola mentions above and already uses logrus.

Just trying to understand it better. As said above, the proposal seems reasonable.

**Comment by bzz** [comment]
@smacker https://github.com/src-d/lookout/pull/9#issuecomment-405318812 explains it well.

👍 Let's implement it and get a logging fixed.

**Comment by smacker** [comment]
> My question was more like, are there any specific cases where you think that would not be enough?

I think there might be such cases but I'm not aware of them. I didn't work with gRPC much. In the past, I used opentracing middleware. It was enough for both dev&prod needs of the project.

The PR contains a workaround using standard go logging (which doesn't require any additional code but formats logs differently). It should be fine during early stages of development. And we can come back to this issue later when we start thinking about proper monitoring.
