### ISSUE TITLE
Fix race conditions

### ISSUE THREAD

**Issue by carlosms** [src-d/lookout#116]
`make test-race` reports too many race conditions.

**Comment by smacker** [comment]
After fixes in tests and logger the only race I see created by:
`vendor/gopkg.in/src-d/go-git.v4/storage/filesystem/dotgit/writers.go:52`

The line:
```go
go writer.buildIndex()
```
https://github.com/src-d/go-git/blob/master/storage/filesystem/dotgit/writers.go#L52

so the race is in go-git and not in our code. Though after quick inspecting go-git code I'm not sure it's really a race...

**Comment by smacker** [comment]
Update: more races were introduced by #128 🤦‍♂️
