### ISSUE TITLE
Include the language name for each File

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/lookout#126]
The current definition in `service_data.proto`:

```proto
message File {
    option (gogoproto.sizer) = false;
    option (gogoproto.protosizer) = true;

    // File path.
    string path = 1;
    // POSIX-style file mode.
    uint32 mode = 2;
    // Hash of the file contents.
    string hash = 3;
    // Raw content of the file.
    bytes content = 4;
    // UAST.
    gopkg.in.bblfsh.sdk.v1.uast.Node uast = 5 [(gogoproto.customname) = "UAST"];
}
```

We have realized that it's not enough: we need to know the language of the file in order to process the UAST correctly.

**Comment by bzz** [comment]
Most probably simplest way would be to add enry support to bblfsh service, in order to get the language and also set it for the bblfhs call.
