### ISSUE TITLE
Create test repository

### ISSUE THREAD

**Issue by smacker** [src-d/lookout#134]
currently, we run tests against src-d/lookout.
it's better to have a special repository for tests that expose simply addressable corner cases (so I don't need to lookup hash in log every time and run diff manually to understand what this test expects).
We also need to test configuration. For that, we need `.lookout.yml` in the repository.

Most probably we can update tests in this task too.

**Comment by bzz** [comment]
Having something similar to https://github.com/git-fixtures/basic  but for the lookout, that is not analyzer-specific would be nice.

>simply addressable corner cases 

Could you please list a few here, just as examples?

**Comment by smacker** [comment]
> Could you please list a few here, just as examples?

from the top of my head:

- PR with delete of a file
- PR with file rename (in separate commit to see if we duplicate comments)
- Empty PR
- PR with unknown language by enry
- PR with unknown language by bblfsh
- PR with empty `.lookout.yml`
- PR with `.lookout.yml` containing unknown analyzer
- PR with `.lookout.yml` and all analyzers disabled
- PR with merge conflict

**Comment by bzz** [comment]
Submodules should be included to mitigate #144 

Tarfile \w bare repository can be included in lookout, to avoid downloading.

**Comment by carlosms** [comment]
One more scenario to test:
- What happens if the github repository gets renamed. We should make sure nothing breaks, and that we don't trigger analysis on already processed events.

**Comment by bzz** [comment]
https://github.com/src-d/lookout-test-fixtures was created, let's use it for now and transfer if necessary later.

**Comment by smacker** [comment]
@carlosms what is the point to have branches from a fork?

here follow-up issues:
https://github.com/src-d/lookout/issues/226
https://github.com/src-d/lookout/issues/228
https://github.com/src-d/lookout/issues/230
https://github.com/src-d/lookout/issues/231

**Comment by carlosms** [comment]
> what is the point to have branches from a fork?

To avoid having only test for PRs that come from the same repo. Maybe we start using a new field from `github.PullRequest` that has some subtle difference. Or maybe it's exactly the same, but then we have fixtures to confirm it.

**Comment by smacker** [comment]
Makes sense. Here is an issue: https://github.com/src-d/lookout/issues/232

**Comment by smacker** [comment]
all basic fixtures are created. Simple go api is implemented.
Complex test cases and more features will be tracked in separate issues.
