### ISSUE TITLE
New go metalinter analyzer

### ISSUE THREAD

**Issue by carlosms** [src-d/lookout#136]
The goal is to have a very simple analyzer that wraps [gometalinter](https://github.com/alecthomas/gometalinter) and returns its response as comments.

This way we could actually make staging environment useful (e.g. that would also enable meaningful user research for product team)

**Comment by bzz** [comment]
gometalinter does no thave and API, only a CLI. 

6 of it's checks work on the file-level, so initial plan is:
 - store `GetChanges()` on local dir and 
 - run only those file-level checks with `exec.Command(gometalinter)`

**Comment by bzz** [comment]
Initial work done under https://github.com/bzz/lookout-gometalint-analyzer

**Comment by bzz** [comment]
Available under https://github.com/src-d/lookout-gometalint-analyzer
