### ISSUE TITLE
[feature] Return the language key, not name

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/lookout#146]
Is it possible to return the key of the language instead of the name in data service responses? E.g. "javascript", not "JavaScript"?

**Comment by smacker** [comment]
we get the name from enry. Enry has no idea about bblfsh language keys.

**Comment by vmarkovtsev** [comment]
@smola I think it is a good idea to ensure that Enry and Babelfish have the same language names.

**Comment by smola** [comment]
@vmarkovtsev AFAIK, all Babelfish language key are lowercased versions of Enry's names.
