### ISSUE TITLE
Comment instead of approve PRs

### ISSUE THREAD

**Issue by bzz** [src-d/lookout#166]
Right now on staging one can see:

<img width="349" alt="screen shot 2018-08-23 at 12 08 10 am" src="https://user-images.githubusercontent.com/5582506/44493543-a764a280-a668-11e8-9c74-a70d6b9b953a.png">

and also

<img width="786" alt="screen shot 2018-08-23 at 12 09 06 am" src="https://user-images.githubusercontent.com/5582506/44493593-db3fc800-a668-11e8-8af9-804f8cf5736f.png">

lookout requesting itself to review the PR is is not expected behavior. 

The expected behavior is: 
 - lookout only post comments (to every new pr), so according to the [docs](https://developer.github.com/v3/pulls/reviews/#create-a-pull-request-review), instead of `approveEvent = "APPROVE"` it should be "COMMENT"
 - only 1 change of PR status to "In Progress" happens, when analysis is not ready yet

**Comment by carlosms** [comment]
> lookout requesting itself to review the PR is is not expected behavior. 

If you are referring to having the bot account in the list of reviewers, I think we can't change that. As soon as the bot makes a comment it will appear as a reviewer.

> The expected behavior is: 
>  - lookout only post comments (to every new pr), so according to the [docs](https://developer.github.com/v3/pulls/reviews/#create-a-pull-request-review), instead of `approveEvent = "APPROVE"` it should be "COMMENT"

Done in #168.

>  - only 1 change of PR status to "In Progress" happens, when analysis is not ready yet

This is how the code is supposed to work right now. If you saw a different behaviour it might be related to the staging re-deployment we did, as we went from a volatile DB to a persistent one... In #168 I don't see any extra status change after the comments were posted, so it might be working fine now, but let's keep an eye on it.

**Comment by bzz** [comment]
>> lookout requesting itself to review the PR is is not expected behavior.
>
> If you are referring to having the bot account in the list of reviewers

indeed, showing up in **Assignees** _with comment_ in GH UI I belive is inevitable, in case of using PR API, which is the only one that allows comments attached to the line numbers, right?

**Comment by carlosms** [comment]
> Did not check, but you basically mean that there is no way to get rid of those guys? 

The status goes from pending to success very quickly, but it's there. If you mean that you'd want the status to disappear instead of changing to success, [I don't think that's possible](https://developer.github.com/v3/repos/statuses/).
