### ISSUE TITLE
Data Service: implement vendor exclusion

### ISSUE THREAD

**Issue by bzz** [src-d/lookout#17]
https://github.com/src-d/lookout/issues/15 introduced `ChangesRequest.ExcludeVendored` flag in Data service API.

This issue is about implementing actual exclusion behaviour for of files, detected by [`enry.IsVendor`](https://godoc.org/gopkg.in/src-d/enry.v1#IsVendor) from the `GetChanges` response.

**Comment by smacker** [comment]
fixed in https://github.com/src-d/lookout/pull/44
