### ISSUE TITLE
Empty language attributes while filing a PR

### ISSUE THREAD

**Issue by m09** [src-d/lookout#176]
## Problem

The `language` attribute of the `File`-s objects returned by `lookout` are empty.

## Steps to reproduce

I followed the instructions at https://github.com/src-d/style-analyzer, with the latest binary or the one matching the version of the `server` submodule and in both cases using the `style-analyzer` repo as the repo to analyze. Same result for both binaries.

## Expected behavior

The `File`-s returned by the `lookout` binary have all their fields set.

## Observed behavior

The `File`-s `language` fields are empty as shown in the logs below:

This logging statement of the `FormatAnalyzer`:

    for file in files:
        cls.log.info("%s %s %d", file.path, file.language, len(file.uast.children))

produced the following log:

```
WARNING:9024:SQLAlchemyModelRepository:created a new database at sqlite:////tmp/lookout.sqlite
INFO:9024:run:Created SQLAlchemyModelRepository(db=sqlite:////tmp/lookout.sqlite, fs=/tmp)
INFO:9024:run:Created DataService(0.0.0.0:10301)
/home/mog/.virtualenvs/style-analyzer/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
INFO:9024:run:Created AnalyzerManager(FormatAnalyzer/1)
INFO:9024:run:Created EventListener(0.0.0.0:2000, 1 workers)
INFO:9024:run:Listening 0.0.0.0:2000
INFO:691d:EventListener:new ReviewEvent
INFO:691d:AnalyzerManager:cache miss: FormatAnalyzer
INFO:691d:AnalyzerManager:training: FormatAnalyzer
INFO:691d:FormatAnalyzer:train file:///home/mog/work/style-analyzer 432e45f88fd386eae4c3608beb83b57880ef30ab {'files': <_Rendezvous object of in-flight RPC>}
INFO:691d:FormatAnalyzer:.flake8  0
INFO:691d:FormatAnalyzer:.travis.yml  0
INFO:691d:FormatAnalyzer:Dockerfile  0
INFO:691d:FormatAnalyzer:LICENSE.md  0
INFO:691d:FormatAnalyzer:README.md  0
INFO:691d:FormatAnalyzer:lookout/__init__.py  3
INFO:691d:FormatAnalyzer:lookout/__main__.py  4
INFO:691d:FormatAnalyzer:lookout/core/__init__.py  0
INFO:691d:FormatAnalyzer:lookout/core/analyzer.py  6
INFO:691d:FormatAnalyzer:lookout/core/api/__init__.py  0
INFO:691d:FormatAnalyzer:lookout/core/api/event_pb2.py  77
INFO:691d:AnalyzerManager:FormatAnalyzer: 1 comments
...
INFO:691d:EventListener:OK 2.576
```

so in-between every path and UAST children count that work as intended, the empty language attribute is (not) displayed.

Here is also the complete `lookout` log: https://gist.github.com/m09/47ede233340156f2850852c3883ddc18

**Comment by bzz** [comment]
@m09 thank you for a report! 

Just to make sure it's reproducible, could you please:
 - provide instructions how to launch everything in same configuration as you did, like e.g in https://github.com/src-d/style-analyzer/issues/30#issuecomment-413628022
 - post, what would be *expected* behavior
 - post, what is *current* behavior instead

this would help to speed up reproducing a problem locally and addressing it asap!

**Comment by m09** [comment]
Thanks @bzz, I reformated to follow an indeed more standard structure.

**Comment by carlosms** [comment]
Reopening until we discuss #187.

Hopefully we'll release a fixed binary today.

**Comment by bzz** [comment]
Everything was merged to master.

Keeping it open for @m09 to verify with a new SDK release.

**Comment by m09** [comment]
Everything works as expected now, cheers :)

**Comment by vmarkovtsev** [comment]
Cool, thanks for this quick fix @carlosms!
