### ISSUE TITLE
Add event-id to every log line in Server

### ISSUE THREAD

**Issue by bzz** [src-d/lookout#181]
To assists debugging e.g cases like https://github.com/src-d/lookout/pull/178#issuecomment-415676512 we need to make sure same event-id is set for as many places we log things, as possible.

This issue is only about server.

Example of logs without event-id
 - gRPCs `connection state changed to 'CONNECTING'`, etc
 - request to https://api.github.com/repos/src-d/lookout/pulls cached"
 - http request to /repos/src-d/lookout/pulls","rate-limit":3985
 - etc.

Related to previous work in https://github.com/src-d/lookout/pull/120 as will require refactoring of some parts to propagate the Context.

**Comment by carlosms** [comment]
Instead of opening a new issue, I'll add here two other things discussed via chat:
- Add the build version. Either to all logs, or at least once when the server starts
- Log the config file read, and environment variables. Probably we want to filter out fields with passwords or tokens

**Comment by smacker** [comment]
some parts of the code don't accept context (git service is a good example). That's why there is no `event-id`. We need to refactor it to support context first.

**Comment by smacker** [comment]
maybe we want to add PR id also. Without it, it's hard to find out on which PR lookout failed. As an example lookout failed here https://github.com/src-d/lookout/pull/221#issuecomment-418671220 but I'm still not sure if it's correct error.

**Comment by carlosms** [comment]
Reopening because I have realized we are still not logging the build version.
