### ISSUE TITLE
Drone will relase lookout docker images for dummy release tags

### ISSUE THREAD

**Issue by carlosms** [src-d/lookout#189]
After the changes in #162 drone uploads the lookout image to dockerhub.
But [the conditions in travis](https://github.com/src-d/lookout/blob/master/.travis.yml#L24) to skip it for `dummy-` tags will not apply anymore.

We can either look for something similar to what we do in `travis.yml`, or move the docker image back to travis. In this case drone would upload images for each commit, and travis for each release.

**Comment by smacker** [comment]
I would better add the condition to drone. To keep image publishing in one place. So we won't end up with publishing the same tag by 2 different systems by mistake :-D
