### ISSUE TITLE
Release a new dummy analyzer docker image

### ISSUE THREAD

**Issue by carlosms** [src-d/lookout#190]
Opening a new issue because there were some changes hidden in #187 discussion.

With the merged code the dummy analyzer does not return comments on push events. This should remove a lot of error messages from the logs in staging.

Before doing the release we need to fix #189.

**Comment by bzz** [comment]
It would be nice to include https://github.com/src-d/lookout/pull/194 to release scope as well.

**Comment by bzz** [comment]
#194 is merged, let's :shipit: !

**Comment by carlosms** [comment]
Released as dummy-v0.0.2
https://hub.docker.com/r/srcd/lookout-dummy-analyzer/tags/
