### ISSUE TITLE
[discussion] Detection of renames?

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/lookout#198]
I have realized that the current API completely ignores the renamed files and it is up to the analyzers to deal with them.

The rename analysis is already implemented in e.g. [Hercules](https://github.com/src-d/hercules/blob/master/internal/plumbing/renames.go#L96) so it should be relatively straightforward to port that code to either go-git or Lookout itself.

WDYT?

**Comment by bzz** [comment]
Yes, as discussed today, the consensus is: lookout would have expose it, in case go-git would provide that information.

As this is not a deterministic process, right now go-git [does not support it](https://github.com/src-d/go-git/blob/3bd5e82b2512d85becae9677fa06b5a973fd4cfb/plumbing/object/patch.go#L316). 

go-git should be able to detect file renames though, in case of no file modifications (but was not able to find a proof-link m.b @smola knows where?)

Rather then implementing it here, a better support of rename detection should be added to go-git directly, and then lookout would benefit from it.

Does it make sense?

**Comment by smola** [comment]
When we added diff-tree to go-git, we agreed that renames would not be part of the internal `utils/merkletrie` package, but that it would supported in go-git's `DiffTree` as a post-processing step over the results of the actual internal diff tree algorithm. We just never got to actually implement it. But yes, I think it should be added to go-git.

git itself is quite flexible, with a few parameters on how to detect renames (e.g. similarity threshold, disabling).

**Comment by bzz** [comment]
Sounds awesome, thanks for prompt clarifications.

Closing if there is no further discussion, but please, feel free to re-open if the case is not closed.

✨ team ✨
