### ISSUE TITLE
[SDK] Data service: expose API for retrieving 1 file

### ISSUE THREAD

**Issue by bzz** [src-d/lookout#21]
For https://github.com/src-d/lookout/issues/20 Lookout server would need to get content of the `.lookout.yml` file from a given reference.

**Comment by smacker** [comment]
Do we really need such API?
Maybe we can use `GetFiles({IncludePattern: "^\.lookout\.yml$"})` at least for now?
What do you think?

**Comment by bzz** [comment]
Indeed as `GetFiles({IncludePattern: "^\.lookout\.yml$"})` would bring a single file, although after iterating all tree objects for a commit with regexp, but it does not require API changes. 

Was thinking about adding API for extracting structured representation of the configuration first, but not sure if that is a responsibility for Data service, so changed to a single file.

**Comment by bzz** [comment]
Will close for now, can re-open later in case we decide to move this responsibility to DataServer
