### ISSUE TITLE
Consider removing the CLI positional argument

### ISSUE THREAD

**Issue by carlosms** [src-d/lookout#229]
The positional argument is not needed at all for the GitHub App auth, we take the list of repos using the API. It should at least be optional.

For the user & token auth we also have a list of repositories in `config.yml`. This is used to configure individual options for each repo, but the list of repos to watch is taken from the positional argument.

This is confusing, and we should probably remove the CLI argument completely and take the list of repos from `config.yml` in the case of user&token auth.

Context in #211.

**Comment by carlosms** [comment]
Important note: this would require to make sure we are configuring the staging deployment correctly before merging, as we redeploy from master automatically.

**Comment by smacker** [comment]
and we will need to update chart

**Comment by carlosms** [comment]
Reopening because of missing docs (from [this comment](https://github.com/src-d/lookout/pull/238#issuecomment-422322752))
> README.md still contains the mentions of <repository> CLI arg and does not mention another way of adding repos

**Comment by smacker** [comment]
David volunteered to fix docs. Assigned the issue to him.

**Comment by carlosms** [comment]
Docs updated in #294.
