### ISSUE TITLE
[SDK] Add simple integration test to CI

### ISSUE THREAD

**Issue by bzz** [src-d/lookout#24]
Add CI profile for integration tests that
 - builds `lookout` binary (part of SDK)
 - launches dummy analyzer `dummy serve`
 - runs `lookout review ipv4://localhost:10302`
 - at least check `grep BEGIN RESULT`
 - runs `lookout push ipv4://localhost:10302`
 - greps for "dummy comment for push event"

Add another profile that verifies that
 - `make protoc` passes
 - `python -m grpc_tools.protoc` as described in https://github.com/src-d/lookout/tree/master/sdk#python passes

**Comment by smacker** [comment]
Implemented
