### ISSUE TITLE
lookout-sdk binary doesn't pick up on config.yml

### ISSUE THREAD

**Issue by m09** [src-d/lookout#269]
It seems that this config file is `lookoutd` specific.

**Comment by smacker** [comment]
why do you need `config.yml` in sdk? It contains configuration specific for `lookoutd`. Or are you talking about `.lookout.yml`?

**Comment by m09** [comment]
I need a `config.yml` in the sdk to have a single source of configuration. Atm I need to copy configuration to all the repositories I analyze which is sub-optimal workflow. I need in particular the `settings` section of `config.yml` when I use `lookout-sdk` and those settings don't change between repos.

**Comment by smacker** [comment]
Got it. But the `config.yml` defines multiple analyzers. Sdk works only with one defined by positional argument. 

Maybe we can add a flag to sdk to read file with `settings` section only. Would it work for you?

@carlosms @bzz wdyt?

**Comment by m09** [comment]
It would be great yes! Just a clarification though, a single analyzer argument in `lookout-sdk` can still ask for several configurations (we have analyzers that are lists of analyzers in `style-analyzer` and each one of them will request its config even though it's exposed as one single analyzer).

**Comment by dpordomingo** [comment]
@m09 was your requirement fully satisfied with the current `--config-json` option?
Do you still miss being able to use the same `config.yml` than when running `lookoutd`?

**Comment by m09** [comment]
It's good enough config-json for me.

**Comment by dpordomingo** [comment]
Since there is no special necessity on passing config in any other way than though `--config-json` we'll close this as agreed by [minutes/419::R87](https://github.com/src-d/minutes/pull/419/files#diff-82137befbf83aa65593b6378ccb848cfR87)
