### ISSUE TITLE
lookoutd binary is not released

### ISSUE THREAD

**Issue by dpordomingo** [src-d/lookout#270]
`lookoutd` binary is not being released.
It is only released the`lookout-sdk` binary under https://github.com/src-d/lookout/releases
In `.travis.yml` file there is [only required the `.sdk` package](https://github.com/src-d/lookout/blob/master/.travis.yml#L76)

**Comment by dpordomingo** [comment]
@bzz could you clarify if is this a desired behavior or just a missing thing?

**Comment by bzz** [comment]
That was intentional, because nobody would use that binary yet.
 It would make sense to add it eventually, as soon as there is a use case. 

We could re-purpose this issue to "release a binary" and move it down in the backlog.
