### ISSUE TITLE
Lookout can not work with private repositories

### ISSUE THREAD

**Issue by dpordomingo** [src-d/lookout#277]
**lookout** can not process private repositories.

It seems to fail at clone phase when it's trying to fetch the repository config from `.lookout.yml`

I ensured that the provided user/token is valid for that user/repo, and the whole app works if the repo is made public again.

```text
ERROR event processing failed app=lookoutd
error=Can't get .lookout.yml in revision: repository not found
{git://github.com/dpordomingo/testing-repo.git refs/pull/54/head 2873cc62558ef48ea506d1c7b87c3a70bcf02989}
event-id=85b1edcc40dc34bdd6e901d513100cb7192f451f
event-type=2 pr-id=216969605 pr-number=54
repo=https://github.com/dpordomingo/testing-repo
```

**Comment by bzz** [comment]
This is a bug indeed - our [Syncer](https://github.com/src-d/lookout/blob/50c807f3ca66225eb9a5a8acb8fb5ffca7496e80/service/git/syncer.go#L32) has no idea about auth token in [cmd/server.go#initDataHandler()](https://github.com/src-d/lookout/blob/50c807f3ca66225eb9a5a8acb8fb5ffca7496e80/cmd/lookoutd/serve.go#L324)

Most probably a simplest way will be to pass in a token and use equivalent of `git clone https://x-access-token:<token>@github.com/owner/repo.git
` as the advice in the [GH Apps docs](https://developer.github.com/apps/building-github-apps/authenticating-with-github-apps/#http-based-git-access-by-an-installation)
