### ISSUE TITLE
Improve observability / error messages

### ISSUE THREAD

**Issue by campoy** [src-d/lookout#287]
Whenever something fails it's very hard to tell why.

For instance, if an analyzer is missing its address the error message is simply "scheme not supported" without any references to what scheme we're talking about.

Similarly logs are not always useful, since there's a very large repetition of pretty useless continuous logs:

```bash
lookout_1   | time="2018-09-24T21:37:33.3683477Z" level=info msg="event successfully processed, skipping..." app=lookoutd event-id=7c712b2e295cda99f96d93a07c009f07e471a28f event-type=2
```

Let's log only things that are meaningful, this line should be `level=debug` if anything.

**Comment by carlosms** [comment]
Note: include the comments about log level from this PR: https://github.com/src-d/lookout/pull/326
