### ISSUE TITLE
Bblfsh fails on second `docker-compose up`

### ISSUE THREAD

**Issue by campoy** [src-d/lookout#288]
It seems like once the volume has been filled with drivers the second run will fail every time.

See `details` for the full logs.

<details>
<pre>
bblfsh_1    | context deadline exceeded
bblfsh_1    |
bblfsh_1    | Usage:
bblfsh_1    |   bblfshctl [OPTIONS] driver [driver-OPTIONS] install [install-OPTIONS] [language] [image]
bblfsh_1    |
bblfsh_1    | Installs a new driver for a given language
bblfsh_1    |
bblfsh_1    | Using `--all` all the official bblfsh driver are install in the
bblfsh_1    | daemon. Using `--recommended` will only install the recommended,
bblfsh_1    | more developed. Using `language` and `image` positional arguments
bblfsh_1    | one single driver can be installed or updated.
bblfsh_1    |
bblfsh_1    | Image reference format should be `[transport]name[:tag]`.
bblfsh_1    | Defaults are 'docker://' for transport and 'latest' for tag.
bblfsh_1    |
bblfsh_1    | Help Options:
bblfsh_1    |   -h, --help              Show this help message
bblfsh_1    |
bblfsh_1    | [driver command options]
bblfsh_1    |
bblfsh_1    |     Manage drivers: install, remove and list:
bblfsh_1    |           --ctl-endpoint= control server network type (default: unix)
bblfsh_1    |           --ctl-address=  control server address to connect (default:
bblfsh_1    |                           /var/run/bblfshctl.sock)
bblfsh_1    |
bblfsh_1    | [install command options]
bblfsh_1    |           --update        replace the current image for the language if any
bblfsh_1    |           --all           installs all the official drivers
bblfsh_1    |           --recommended   install the recommended official drivers
bblfsh_1    |           --ctl-endpoint= control server network type (default: unix)
bblfsh_1    |           --ctl-address=  control server address to connect (default:
bblfsh_1    |                           /var/run/bblfshctl.sock)
bblfsh_1    |
bblfsh_1    | [install command arguments]
bblfsh_1    |   language:               language supported by the driver
bblfsh_1    |   image:                  driver's image reference
bblfsh_1    |
bblfsh_1    | Build information
bblfsh_1    |   commit: v2.5.0
bblfsh_1    |   date: 2018-06-05T11:39:45+0000
</pre>
</details>

The solution for me was to delete the `lookout_drivers` volume in between runs.

**Comment by carlosms** [comment]
For now I've added `docker-compose --force-recreate` to the docs as a workaround.
https://github.com/src-d/lookout#running-lookout-with-docker-compose

I hope https://github.com/bblfsh/bblfshd/pull/188 will make this more robust.
