### ISSUE TITLE
docker compose: config.yml is a folder

### ISSUE THREAD

**Issue by campoy** [src-d/lookout#289]
Due to the way `config.yml` is mounted into to Docker, when the file doesn't exist in the current directory it is mounted as an empty directory.

This leads to the following error message:

```bash
lookout_1   | Can't open configuration file: read config.yml: is a directory
```

I propose solving this by either:
- providing an empty `config.yml`, or
- changing the code to ignore `config.yml` if it's not a file.

**Comment by campoy** [comment]
I think the problem is that when the file doesn't exist it ends up being created as a directory.
Is there any way to avoid that behavior?

I'd rather have an error saying something like "no analyzers found in config.yml" than this

**Comment by carlosms** [comment]
I couldn't find a way to detect the file before launching the containers, so in #320 I've added a better error message for this specific scenario.
