### ISSUE TITLE
Force push does not trigger lookout

### ISSUE THREAD

**Issue by meyskens** [src-d/lookout#301]
When using the GitHub app:
1) Create a PR from a branch
2) Force push a `git commit --amend` to the branch

Lookout does check the PR the first time when pushing the change.

**Comment by meyskens** [comment]
(tested using staging)

**Comment by carlosms** [comment]
Thanks for reporting this, it's a known limitation. We don't process incremental changes made to PRs yet.
See https://github.com/src-d/lookout/issues/259.
