### ISSUE TITLE
Extend the protocol to provide the ability to parse arbitrary code

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/lookout#339]
We are developing the format analyzer. We hit the following problem: our analyzer may suggest code which is completely wrong, up to the point that it is not parsed to the same AST or not parseable at all. We don't want to suggest garbage, of course, so we need to parse the suggested variant and compare the old and the new ASTs. However, Lookout protocol does not allow to parse arbitrary code, only by specific Git revision. Our workaround is to invoke Bablefish directly, which breaks the whole abstraction.

I request an extension of the protocol which is basically a thin proxy layer between the Lookout server and the Babelfish server. We need the old, "v1" UASTs in Q4. More specifically: given a file name and it's contents, return the UAST. We are totally fine with batching.

**Comment by smacker** [comment]
@smola this feature request is a little bit controversial, could you please approve it before we start implementing it?

**Comment by smola** [comment]
Analyzers definitely need to access this API, whether it is on lookout itself or not.
I think we recently agreed that it would be exposed in the lookout API, @mcuadros is that right?

**Comment by vmarkovtsev** [comment]
Decision on the meeting today:

- We will proceed with proxying bblfsh API from the lookout data server.
- We will consider later on if lookout should provide a higher level API to do sanity checks on suggested changes from analyzers.

**Comment by carlosms** [comment]
A comment on the solution, from slack conversations:
Lookout will proxy the gRPC methods to bblfsh. The analyzers will be use a regular bblfsh client, which will be initialized with some new helper method in lookout-sdk.

**Comment by carlosms** [comment]
Reopening since I have just realized we don't have any docs for the new feature.

**Comment by smacker** [comment]
There is pull request waiting for release of new version:
https://github.com/src-d/lookout-sdk/pull/29

Or do you think we also need them in this repository?

**Comment by carlosms** [comment]
Let me think about it, but probably that's enough taking into account we are in the process of migrating everything over to GitBook.

**Comment by carlosms** [comment]
Releasing in a few minutes :)
