### ISSUE TITLE
Turn off lookout by default - expect .lookout file per repo.

### ISSUE THREAD

**Issue by kuba--** [src-d/lookout#344]
Original idea was to have a lookout running per repo(s) by yourself. But over the time it turned on that lookout should be treated like CI services, etc.
If you have a lookout running by yourself it makes sense to have it turned on by default and you shouldn't have any extra config files.
But if we take a approach that **lookout** is a service running somewhere in the cloud (e.g. GCE) for all repos/orgs. then it should be turned off by default. In this case (to turn it on), you should be able to control it with config file. I believe having an extra .lookout file per repo is not a big deal (we already have a bunch of meta-files, like .travis.yml, appvoyer.yml so one more is not a big deal).

**Comment by dpordomingo** [comment]
@carlosms would the requested behavior be covered by source{d} Lookout Web-UI and GitHub Apps?
If so, could be this issue superseded by https://github.com/src-d/lookout/issues/403?

**Comment by carlosms** [comment]
Yes, I'd say #403 will cover this request, although not in the same way as described. Closing.
