### ISSUE TITLE
Add default host and port on lookout-sdk review

### ISSUE THREAD

**Issue by smola** [src-d/lookout#350]
I assume that the general case is that we're testing an analyzer locally and on the default port (`2022`?). So we could just have `ipv4://0.0.0.0:2022` as the default analyzer to check.

**Comment by smacker** [comment]
currently there is no default port for analyzers:

dummy: [10302](https://github.com/src-d/lookout/blob/master/cmd/dummy/main.go#L22)
gometalint: [2001](https://github.com/src-d/lookout-gometalint-analyzer/blob/master/cmd/gometalint-analyzer/main.go#L34)
sonarcheck: [2022](https://github.com/src-d/lookout-sonarcheck-analyzer/blob/master/sonarcheck_analyzer.py)
terraform: [2020](https://github.com/src-d/lookout-terraform-analyzer/blob/master/main.go#L12)
style: [2000](https://github.com/src-d/style-analyzer#how-to-use)

shall we choose one and update all?

**Comment by smola** [comment]
Yes, I think so, it would be in line with other efforts we are making to choose good default ports. If we have to make an arbitrary choice, I propose 9930 (random 4-digit port number without an entry [known to nmap](https://svn.nmap.org/nmap/nmap-services)).

**Comment by smacker** [comment]
Current status:

- [x] lookout-tool
- [x] dummy
- [x] gometalint
- [x] sonarcheck
- [ ] terraform (PR created)
- [ ] style (doesn't have default number, requires explicit number in configuration, PR with documentation update to 9930 as recommended created)

**Comment by smacker** [comment]
I think we can close this issue.

- Default port support in lookout-tool was implemented
- All analyzers with default port were updated
- Style-analyzer doesn't have default port but documentation update was suggested. (style-analyzer doesn't belong to us so it's up to ML team to merge update or not)
