### ISSUE TITLE
Log fields are lost when events are sent to the queue

### ISSUE THREAD

**Issue by carlosms** [src-d/lookout#357]
The log fields added in https://github.com/src-d/lookout/pull/245 were lost when we introduced the queue. Once the job is dequeued, it does not keep the context with the log Fields.

**Comment by zurk** [comment]
I think I hit the same problem with `lookout-sdk`. 
When I run something like
```bash
lookout-sdk push --log-level=warning ...
```
or 
```bash
lookout-sdk push --log-level dedug ...
```

Anyway, I get `info` log level. 

@src-d/applications can you confirm it is the same bug or should I create a new issue?

**Comment by carlosms** [comment]
No @zurk, the log level initialization is not related to the original description. Please open a new issue.
