### ISSUE TITLE
Deal with top level errors in a consistent way

### ISSUE THREAD

**Issue by carlosms** [src-d/lookout#362]
Some errors trigger a `os.Exit`, others are returned and managed with channels in the top CLI level, like [here](https://github.com/src-d/lookout/blob/1f29d62aba5de00a3fc76094229de3bf050b146e/cmd/lookoutd/serve.go#L96).

Context here: https://github.com/src-d/lookout/pull/361#discussion_r235340499

@carlosms 

> What I was thinking is that maybe this method should be blocking, removing `go func` and directly do `return grpcSrv.Serve`. Then on top handle it like here https://github.com/src-d/lookout/blob/master/cmd/lookoutd/serve.go#L96. WDYT? is it worth to make it consistent with other top level errors, so we have one clear exit point?

@smacker 

> We use this function not only in `serve.go` but in worker too. It doesn't use chan/switch pattern. SDK uses a similar pattern but instead of making the methods blocking it accepts chan as an argument. 
> 
> Though I like your idea to make it consistent, I'm not sure which pattern we should use.

**Comment by smacker** [comment]
I would prefer using blocking functions and add concurrency on the top level. It's also aligned with [CodeReviewComments](https://github.com/golang/go/wiki/CodeReviewComments#synchronous-functions).
