### ISSUE TITLE
repository not found

### ISSUE THREAD

**Issue by smacker** [src-d/lookout#365]
Maybe private repositories cloning is broken?

<img width="840" alt="screenshot 2018-11-22 at 20 45 25" src="https://user-images.githubusercontent.com/406916/48920168-a0337780-ee97-11e8-9545-6d8f1b71f721.png">

**Comment by smacker** [comment]
After debugging I couldn't find any problem in lookout.
At the end, I generated token using staging private key. And:
```
$ git clone https://x-access-token:[TOKEN]@github.com/src-d/infrastructure.git
Cloning into 'infrastructure'...
remote: Repository not found.
```

Most probably the app lacks `content` access to the repository. @src-d/infrastructure please confirm.

**Comment by rporres** [comment]
These are the permissions that https://github.com/apps/lookout-staging has over src-d code

![image](https://user-images.githubusercontent.com/2647973/49278108-16ca0980-f484-11e8-85d4-5e4296a5cbe3.png)

This is what you mean when you say the app lacks `content` access, @smacker?

**Comment by meyskens** [comment]
@smacker this were the permissions I applied: https://github.com/src-d/issues-infrastructure/issues/233

**Comment by smacker** [comment]
Yes. We introduced support for private repositories after that ticket was created. 
Lookout needs access to read content of a repository to be able to clone it. Please add it.

**Comment by rporres** [comment]
We need @mcuadros superpowers for this

**Comment by carlosms** [comment]
@smacker please check if we also need to update our docs

**Comment by smacker** [comment]
As proposed by David/Carlos moved to infra repo: https://github.com/src-d/infrastructure/issues/249
I'm closing this one.
