### ISSUE TITLE
lookout-sdk --log-level flag does not work

### ISSUE THREAD

**Issue by zurk** [src-d/lookout#374]
Originally I posted a comment to this issue https://github.com/src-d/lookout/issues/357#issuecomment-443360296 but @carlosms says it is unrelated so here is a new one.

There is a problem with `lookout-sdk` `--log-level` flag. It looks like it does not affect log level at all.

When I run something like
```bash
lookout-sdk push --log-level=warning ...
```
or 
```bash
lookout-sdk push --log-level debug ...
```

Anyway, I get `info` log level. 

Small examples to reproduce:
```bash
➜ lookout-sdk version  
lookout-sdk v0.5.0 built on 11-23-2018_16_43_04
➜ lookout-sdk push -v ipv4://localhost:2000 --from aaa --to bbb --git-dir . --log-level=warning
[2018-12-01T01:46:43.181913214+03:00]  INFO resolving to/from references app=lookout-sdk source=lookout-sdk/event.go:58
base revision 'aaa' error: reference not found
➜ lookout-sdk push -v ipv4://localhost:2000 --from aaa --to bbb --git-dir . --log-level warning
[2018-12-01T01:47:05.522527611+03:00]  INFO resolving to/from references app=lookout-sdk source=lookout-sdk/event.go:58
base revision 'aaa' error: reference not found
```
You can see `INFO` log messages.

**Comment by carlosms** [comment]
For historic reasons the `-v/--verbose` option ended up being used to set the log level to `debug`, and nothing more. If you stop using `-v` you'll see the log level is applied.
