### ISSUE TITLE
Warnings on docker-compose pull

### ISSUE THREAD

**Issue by erizocosmico** [src-d/lookout#384]
These warnings are printed when you use `docker-compose pull` as described in the README. It may be a little weird for the user to see them when at no point they're said to be required.

```
WARNING: The GITHUB_USER variable is not set. Defaulting to a blank string.
WARNING: The GITHUB_TOKEN variable is not set. Defaulting to a blank string.
```

**Comment by dpordomingo** [comment]
@erizocosmico this issue should be addressed by https://github.com/src-d/lookout/pull/405

**Comment by dpordomingo** [comment]
already merged into `master`
feel free to reopen if it does not fit you @erizocosmico
