### ISSUE TITLE
Docs missing on how to run your own analyzer with the provided docker-compose

### ISSUE THREAD

**Issue by erizocosmico** [src-d/lookout#387]
I tried running everything with docker compose a before. Changed `config.yml` to add my analyzer with the URL `ipv4://localhost:2020` as said on the docs. Lookout could not connect to it. Presumably because of docker networking mumbo jumbo. Again, some guidance should be provided on how to do this with docker-compose if we offer that option to the users.
I ended up resorting to manual deploy of all services because I could not figure out how to make this work with docker-compose.

**Comment by dpordomingo** [comment]
@erizocosmico this issue should be addressed by #407
