### ISSUE TITLE
Log in with GitHub accounts

### ISSUE THREAD

**Issue by carlosms** [src-d/lookout#399]
Umbrella issue, depends on #397.
This issue is to implement the basics for GitHub user login, with the following tasks:
- [x] GitHub Oauth login:
  - Serve a `/login` screen with a "login with GitHub" button
  - Endpoint in the server to perform the login using OAuth. This can be similar to what we do in https://github.com/src-d/code-annotation
  - If the login is successful we redirect to `/`; if not to `/unauthorized` (or similar name). For now it can be a blank page with a simple "authenticated"/"authentication error" text.
- [x] Manage access authorization and sessions
  - The server will return a JWT
  - The client will save it in localStorage
  - Unauthorized access to `/` should redirect to `/login`
  - A client should be able to access `/` directly if the token is valid
  - The `/` page will have a "log out" button

**Comment by smacker** [comment]
done
