### ISSUE TITLE
Release a new dummy analyzer docker image

### ISSUE THREAD

**Issue by dpordomingo** [src-d/lookout#406]
The dummy analyzer default port was changed from `10302` to `9930` by #389.
The latest dumy release [`dummy-v0.0.3`](https://github.com/src-d/lookout/releases/tag/dummy-v0.0.3) uses the old port `10302` so lookout cannot be run with the recommended way: `docker-compose up`.

It is needed to release a new [dummy image](https://hub.docker.com/r/srcd/lookout-dummy-analyzer/tags/)

**Comment by smacker** [comment]
Here you go: https://hub.docker.com/r/srcd/lookout-dummy-analyzer/tags/
