### ISSUE TITLE
Proposal to pass settings to the analyzers using lookout-sdk

### ISSUE THREAD

**Issue by dpordomingo** [src-d/lookout#422]
# Problem to solve:

>https://github.com/src-d/lookout/issues/269 _`lookout-sdk` binary doesn't pick up on `config.yml` as `lookoutd` does._
>_I'd need a `config.yml` in the sdk to have a single source of configuration._

<a id=current-proposal></a>
## Current proposal

`lookoutd` already takes as a default conf `config.yml`, but you can change it
- `--config=config.yml`

`lookout-sdk` will need to pass ONLY one of the following combinations
- `--config=config.yml`
- `--config-json={"key":"value"} ipv4://localhost:9930` (caused by https://github.com/src-d/lookout/issues/274)

The same `config.yml` file, used for `lookoutd`, could be used with `lookout-sdk`, but:
- If it defines more than one analyzer, it will fail;
- `providers`, `repositories` and `timeout` are ignored;
- `analyzers.name` and `analyzers.feedback` keys will be ignored;

example
```yml
analyzers:
  - addr: ipv4://localhost:9930
    settings: # whatever config to pass to the analyzer
```

<a id=LIP01></a>
## LIP01. Define many analyzers.

Based on the [current proposal](#current-proposal), the goal would be to make the same `config.yml` file compatible with both `lookoutd` and `lookout-sdk`.

It should be able to define more than one analyzer in `config.yml`, and calling one at will using the new command option `--analyzer=name`; `lookout-sdk` will call the analyzer identified by `analyzers.name`.

If many analyzers are defined in `config.yml`, but no one is specified with `--analyzer` option, `lookout-sdk` will `exit 1` and hint with `--analyzer` option and the list of the names of the defined analyzers.

###  Rename `config-json` option to `settings`

Since the meaning of that option, is to pass the settings to the analyzer (as done by `config.yml`, it would be better if the command option is renamed to `--settings`.

If there is already defined settings in the `config.yml`, they would be deep merged applying the same rules than with `.lookout.yml`; that way it would not be neccessary to force only one option to pass the settings to the analyzer; both: `--config` and `--settings`, could be used.

## LIP02. Call many analyzers.

Based on the [LIP01](#LIP01), the goal would be being able to call many analyzers from `lookout-sdk` as `lookoutd` does.

It might be done, for example through `--analyzer=name1,name3`, so `lookout-sdk` would call the analyzers identified as `name1` and `name3`; passing no name, will call all of them.

It would mean that `lookout-sdk` is a kind of `cli` version of `lookoutd`. I think it'd be a nice-to-have option but it might require bigger changes to reuse `lookoutd` code.

**Comment by smacker** [comment]
1. what is the use case for calling many analyzers from lookout-tool?

Since the beginning of the project and as a maintainer of few analyzers I never needed such function. It also goes against the original purpose of lookout-tool.

2. I agree `--settings` would be better name than `--config-json`. 

3. Does any user still request usage of `config.yml` instead of `--config-json`? (the issue mentioned above was created before `--config-json` was introduced)

**Comment by dpordomingo** [comment]
1. then just discard `LIP02` ;)
but I think it could be useful to run `lookoutd` as a CLI tool.
One possible use case could be:
   >_please lookout, run these analyzers over this bunch of commits and save the report in this log file_
2. :+1: 
3. as a user, I'd like to use **the same file** in `lookout-sdk` than in `lookoutd` because hundreds of reasons (example: to locally **test the same setting** that are already running in the `lookoutd` instance that is already posting comments into GH; then modify them; locally try them again; and then commit; instead of changing format from inline `json` to `.yml` file, back and forth)

**Comment by smacker** [comment]
> CLI tool

interesting case. 👍 
But maybe not for the current lookout-sdk tool as it's for testing.
Though I like the idea for the future as part of lookoutd or separate command.

> I'd like to use the same file

still don't get why. If you are already working with lookoutd server you can always run it as `dry-run` with new config. 

I try to explain that from my understanding lookout-sdk bin and lookoutd are not interchangable. They have different use cases:
- use lookout-sdk when you develop analyzer
- use lookoutd when you want to run your own review server

There is no need for an analyzer developer to use lookoutd ever.
And there is no need for lookoutd admin to use lookout-sdk.

Btw in the original issue Hugo just reported that `--config-json` is good enough for him.

**Comment by dpordomingo** [comment]
I'd only add `--config` option to `lookout-sdk` if it is for making it more compatible with the config file already used by `lookoutd`. Otherwise, I think it could lead to more confusion between these two binaries, so in that case I'd suggest closing this #422, #269 and #415.

**Comment by dpordomingo** [comment]
Since there is no special necessity on passing config in any other way than though `--config-json` we'll close this as agreed by [minutes/419](https://github.com/src-d/minutes/pull/419) at [R87](https://github.com/src-d/minutes/pull/419/files#diff-82137befbf83aa65593b6378ccb848cfR87)
