### ISSUE TITLE
Add binaries for windows

### ISSUE THREAD

**Issue by smacker** [src-d/lookout#46]
Follow up for #23 

Currently, we focus on ML team needs so Linux/MacOS is enough but according to the [conventions](https://github.com/src-d/guide/blob/master/engineering/conventions.md#operating-system-support) we should support Windows also.

**Comment by bzz** [comment]
That sounds good, thank you for creating an issue - let's keep it open but it is not yet a priority.

**Comment by carlosms** [comment]
Closing in favor of #499.
