### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by smacker** [src-d/lookout#47]
1. All commands (serve/review/push/dummy) should have `-v` flag.
2. When logging is verbose successful path should be printed. It includes at least `Connected to`, `Send`/`Revieved` event. For servers it should reports when a server has started. Please inspect the code to make find more useful cases.
3. What should we do with grpc logging? There was a suggestion to replace it with our logging: https://github.com/src-d/lookout/pull/37#issuecomment-406548743 @bzz @carlosms need your input
4. We may also want to be able to configure level more flexible. Example: https://github.com/smola/go-cli/pull/1/files#diff-308aaa719425f4333033c97cfb3b9868
5. review/push/(dummy?) should have INFO level by default while serve most probably WARNING. -v flag would make it one level more versbose

**Comment by bzz** [comment]
Proposal looks solid.

> 3. What should we do with grpc logging? There was a suggestion to replace it with our logging: #37 (comment) @bzz @carlosms need your input

I would say custom gPRC logging is important right now for SDK case, and for me suggesting for #37 holds for that case in particular. May be middleware-based logging would allow for exactly this granularity?

For `serve`, I would say if we want to keep current super-verbose logs - we need to add `-vv` and m.b apply  #11 ?

**Comment by smacker** [comment]
For `serve` maybe something similar to configuration from `go-cli` would work?
(actually I would better copy-past than it will be easier to migrate to `go-cli` later)

**Comment by bzz** [comment]
Personally, I'm mostly concerned with SDK usability for now - we should build the trust for the initial users so there is no need for them to double-check networking accessibility and always be able to tell what's going on for review/push.

On `serve` I'm not sure what do you mean with go-cli - could you give an example? `-vv` looks common for CLI tools

**Comment by smacker** [comment]
The example is in the link attached to the issue description 🤔 . Once again: https://github.com/smola/go-cli/pull/1/files#diff-308aaa719425f4333033c97cfb3b9868

For the successful case, the only thing left is grpc logs in verbose mode. For error case, we need to wrap errors in more human-friendly format also. If you feel grcp-middlleware is a good fit for that, let's implement it. (PRs are welcome)

But for flags, env vars, ... I think here is no conclusion, in my opinion. I would prefer to follow our guidelines [for configuration](https://github.com/src-d/guide/blob/master/engineering/conventions.md#configuration) than `-vv` or any other custom flags.

And instead of inventing such configuration I would copy-past it from go-cli to simplify our life in the future.

Quote @smola:
> I'll move to src-d/go-cli or src-d/go-app once it's ready
