### ISSUE TITLE
[feature request] Remove deadline for the very first review event

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/lookout#500]
Here is what happens:

1. Lookout discovers a PR in a *brand new repository*
2. It triggers style-analyzer
3. It starts training the model, which takes a few hours
4. `level=error msg="analysis failed" analyzer=format app=lookoutd error="rpc error: code = DeadlineExceeded` - apparently
5. style-analyzer eventually finishes training the model, but cannot send the first review results

My proposal how to make it work: if we see that the repository has not been analyzed at least once yet, we should remove the timeout.

**Comment by smacker** [comment]
I would propose another solution, you can train in the background and just return empty comments.
You mentioned before, training on node takes 6h+. It would be strange to keep an open connection for 6 hours that can get broken anyway (due to network or redeployment of lookout or whatever).

**Comment by smacker** [comment]
Also, we can't know if it's the very first review or not.
Lookout can work with a repository for months before deployment of the style-analyzer for which it will be "the very first" PR. Or if style-analyzer loose model by any reason it will have to retrain too and lookout can't know about it. At least with the current API.

**Comment by vmarkovtsev** [comment]
Training in background changes closely to everything in the architecture on our side. We are going to need a process pool (Python has a GIL), balance it, etc. This means Celery or other heavy artillery and many many non-ML problems nobody wants to deal with in the team.

**Comment by vmarkovtsev** [comment]
@smola If we wish to fix it on lookout-sdk-ml side, we need to hire good Python senior devs to sort it out because currently it's only me who can dig the problem and I don't have the required bandwidth.

**Comment by se7entyse7en** [comment]
I agree with @smacker regarding keeping an open connection for 6h+ and I think it's a good idea to do the training in the background. Anyway I like to consider myself a good Python dev 😅, but I don't know what's your idea of Senior, but maybe in the meantime if you want maybe I might help (I don't know if there are somebody else having more experience in Python actually). I've worked with Celery to run both scheduled and non-scheduled tasks on a cluster of workers. I also have experience in running standalone microservices as daemons both using multiple processes (due to the GIL) and both on multiple servers, by consuming a queue (Kafka in my case) containing the informations of the jobs to perform.

**Comment by vmarkovtsev** [comment]
This is an interesting proposal @se7entyse7en, thank you for help! We should discuss everything next week provided by Santiago approves.

**Comment by carlosms** [comment]
We will have a design doc to integrate the need for a long training process into lookout.

Meanwhile, what I propose as a workaround is: make a requirement of any style analyzer installation to remove lookout timeouts, [setting `0` in the config file](https://docs.sourced.tech/lookout/configuration#timeouts).

**Comment by vmarkovtsev** [comment]
@smola @carlosms Has a DD been written? This is still blocking us.

**Comment by dpordomingo** [comment]
imo it could be a good idea to reopen this issue to track and communicate any progress on this feature request.

**Comment by carlosms** [comment]
I agree we should have a place to track this task. But I'm not sure it should be this issue. There is a pending design doc for the initial pain point that motivated this request, but the feature as requested here will not be implemented.

I will open an issue in feature-idea. That will eventually go to backlog, and from there we'll open the needed issues here.
