### ISSUE TITLE
Add configurable gRPC size limit

### ISSUE THREAD

**Issue by bzz** [src-d/lookout#52]
Every part that performs serving gRPC should have a configuration `--grpc-max-message-size` with default set to 100Mb (and reasonable max limit i.e 2Gb)

Right now these are:
  - dummy analyzer
  - server, data server

See bblfshd as example https://github.com/bblfsh/bblfshd/blob/566a2465591049b0679c4ae1b454e9fd9f0111e0/cmd/bblfshd/main.go#L152

**Comment by smacker** [comment]
I added hard-coded limit for call: https://github.com/src-d/lookout/pull/44/commits/e6023c5abd1a694a790afc37ee34aa10b5fff6d5 to pass CI. But we also need to add [MaxRecvMsgSize ServerOption](https://godoc.org/google.golang.org/grpc#MaxRecvMsgSize) also and make it configurable.
