### ISSUE TITLE
Failing test TestServerTestSuite/TestPushTimeout

### ISSUE THREAD

**Issue by carlosms** [src-d/lookout#537]
Failing on master (626408f), from travis logs on `make coverage`
```
    --- FAIL: TestServerTestSuite/TestPushTimeout (0.01s)
        require.go:738: 
            	Error Trace:	server_test.go:173
            	Error:      	"[text:"base-hash > head-hash" ]" should have 0 item(s), but has 1
            	Test:       	TestServerTestSuite/TestPushTimeout
```

The tests passed after a travis job restart.

**Comment by se7entyse7en** [comment]
I was able to reproduce it 🎉

**Comment by se7entyse7en** [comment]
Okay! I found the problem. It's simply an OS limitation 😄. Take a look [here](https://github.com/golang/go/issues/260). By looking around it seems that on average a non-realtime OS can sleep for a minimum amount of time that ranges from 1ms to 10ms. In this test there's a 1ms timeout and a sleep of 5ms to force a context cancellation, but evidently sometimes we hit this limitation. I'm gonna fix this by increasing the timeouts.
