### ISSUE TITLE
lookout-sdk: if uast is not wanted, language is not set

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/lookout#559]
If we are using the data service in `lookout-sdk` and pass `want_uast=false`, `want_contents=true` (either FilesRequest or ChangesRequest), then the language of each returned file is not set. We really want the language in this case.

**Comment by carlosms** [comment]
Hi, please try the [`want_language`](https://github.com/src-d/lookout-sdk/blob/master/proto/lookout/sdk/service_data.proto#L90) flag in the request.

**Comment by vmarkovtsev** [comment]
Cool, didn't know it existed. Thanks.
