### ISSUE TITLE
Update to Go 1.12

### ISSUE THREAD

**Issue by dpordomingo** [src-d/lookout#583]
Since [Go 1.12 is already there](https://blog.golang.org/go1.12) and both `Go v1.11` and `Go v1.12` supports [Go Modules](https://github.com/golang/go/wiki/Modules), we could also [update `.travis` to `v1.12.x`](https://github.com/src-d/lookout/blob/master/.travis.yml#L22) and migrate from `dep` to `go mod`

**Comment by smacker** [comment]
I would wait until we update go-conventions: https://github.com/src-d/guide/blob/master/engineering/conventions/go.md

**Comment by carlosms** [comment]
I'm going to edit this issue to drop `go mod` and focus on go 1.12. We need to check travis, and the base docker images.

**Comment by dpordomingo** [comment]
but then we need another issue for `go mod` migration

**Comment by carlosms** [comment]
But we can open it when the conventions guidelines are updated, don't you think?

**Comment by dpordomingo** [comment]
I understood that it was a thing to do from a message from @smola on company Slack channels.

**Comment by carlosms** [comment]
Alright, then feel free to open a new issue for `go mod`. I guess we may have things to discuss (vendor vs no vendor for instance), while the go 1.12 is straightforward and should not depend on the `go mod` discussion.

**Comment by smacker** [comment]
agree with Carlos on that. There is also a question about `go mod tidy` for example.

**Comment by dpordomingo** [comment]
When I opened this issue I considered it would be like an umbrella for such different tasks and discussions... but ok, [here is the new issue](https://github.com/src-d/lookout/issues/592).
