### ISSUE TITLE
Add binaries for Linux

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/lookout#62]
https://github.com/src-d/lookout/blob/master/sdk/README.md points to https://github.com/src-d/lookout/releases which is

![image](https://user-images.githubusercontent.com/2793551/43215751-53950a3c-903d-11e8-840a-1cd9e7502357.png)

**Comment by bzz** [comment]
Thank you for kind reminder! 

🎉  https://github.com/src-d/lookout/releases/tag/v0.0.1
