### ISSUE TITLE
lookout client sends negative seconds

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/lookout#67]
I execute `./lookout review ipv4://localhost:2000` and receive the request on Python side. I get the following `ReviewEvent`:

```
created_at {
  seconds: -62135596800
}
updated_at {
  seconds: -62135596800
}
```

Indeed, those integers are negative.

**Comment by bzz** [comment]
Indeed, those fields `lookout review` should emulate an event created right now, so it makes sense to initialize those fields with `time.Now()`
