### ISSUE TITLE
Naming inconsistency in event proto

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/lookout#68]
Abstract from `sdk/event.proto`:

```
message ReferencePointer {
    // InternalRepositoryURL is the origina; clone URL not canonized.
    string internal_repository_url = 1 [(gogoproto.customname) = "InternalRepositoryURL"];
    // ReferenceName is the name of the reference pointing.
    string ReferenceName = 2 [(gogoproto.casttype) = "gopkg.in/src-d/go-git.v4/plumbing.ReferenceName"];
    // hash is the hash of the reference pointing.
    string Hash = 3;
}

// PushEvent represents a Push to a git repository.
message PushEvent {
    // Provider triggering this event.
    string provider = 1;
    // InternalId is the internal id for this event at the provider.
    string internal_id = 2 [(gogoproto.customname) = "InternalID"];
    // CreateAt is the timestamp of the creation date of the push event.
    google.protobuf.Timestamp created_at = 3 [(gogoproto.nullable) = false, (gogoproto.stdtime) = true];
    // Commits is the number of commits in the push.
    uint32 commits = 4;
    // Commits is the number of distinct commits in the push.
    uint32 distinct_commits = 5;
    // Configuration contains any configuration related to specific analyzer
    google.protobuf.Struct configuration = 6 [(gogoproto.nullable) = false];

    CommitRevision commit_revision = 7 [(gogoproto.nullable) = false, (gogoproto.embed) = true];
}
```

We've got two different naming conventions here: `lower_underscore` and `UpperCamelCase`. I am fine with both but please choose the one and rename everything else accordingly.

**Comment by smola** [comment]
According to [Google's protobuf style](https://developers.google.com/protocol-buffers/docs/style#message-and-field-names):

> Use CamelCase (with an initial capital) for message names – for example, SongServerRequest. Use underscore_separated_names for field names – for example, song_name. 

Let's follow that for the protos. Comments are a bit more tricky since I guess we are just naming fields after their Go counterparts after codegen. I wonder if Go protobuf code generation is able to convert names in comments too.

**Comment by bzz** [comment]
Thank you for inquiry @vmarkovtsev and quick clarification @smola !

Closing, as following exciting Protobuf conventions makes perfect sense

**Comment by vmarkovtsev** [comment]
Yep, thank you @smacker - exactly what I noted at.

**Comment by bzz** [comment]
Nice catch! 👍 
Would somebody please be able to re-word the PR description to make it actionable?
