### ISSUE TITLE
Deploy to staging environment

### ISSUE THREAD

**Issue by bzz** [src-d/lookout#80]
As part of Phase1 of development, we want to have a staging environment analyzing repositories under src-d org.

TODOs:
 - prepare contains + instructions to run them #79 
 - [ask Infra](https://github.com/src-d/minutes/pull/293/files#diff-0b21715419b1be0390a5f9efbb33bc0fR25) by creating an issue \w request for a 
   * chart: deployment? for server, a service for Dummy analyzer + bblfsh + postgres. (later, another service for Style analyzer will be added)
   * staging env (Infra choice, most probably our pipeline cluster?)
   * CD system (Infra choice)
 - configure
    * point to 2 repositories: https://github.com/src-d/lookout/ and https://github.com/src-d/style-analyzer
    * use GH token \w write access to those repos (Alex or Santiago should be able to provide one)
    * use Dummy analyzer
 - cut release and deploy

**Comment by bzz** [comment]
On CD of latest master, we need to handle migrations gracefully
 - run migrations in separate container
 - restart server container

**Comment by smacker** [comment]
We created docker images and working docker-compose file.
The issue for infra:
https://github.com/src-d/issues-infrastructure/issues/213

Most probably stuff about travis/drone/CD should be discussed there.

**Comment by bzz** [comment]
- ✅ deployment https://github.com/src-d/issues-infrastructure/issues/213#issuecomment-413592033
 - [ ] fix #147 
 - ask Rafa to deploy it again

**Comment by bzz** [comment]
Let's fix staging first, errors:
 - https://github.com/src-d/issues-infrastructure/issues/213#issuecomment-414632222
 - anything else from `kubectl logs lookout-1292344853-3l0c5`

**Comment by bzz** [comment]
We can close this one, as soon as a manually deployed staging is operational.

Automation of CD tracked under separate #160
