### ISSUE TITLE
Remove merge field from review event

### ISSUE THREAD

**Issue by smacker** [src-d/lookout#83]
This field is very confusing when you study proto files and the current behavior of this field bound to GitHub. Other providers have a similar field but with the different meaning. It contains sha of merge commit ONLY AFTER pull request is merged. Before it's empty.

According to discussions we don't need this field (at least for the first version of the service/analyzers) because we don't need to comment on closed pull requests.

**Comment by dpordomingo** [comment]
@smacker  Is this about dropping this proto property https://github.com/src-d/lookout-sdk/blob/master/proto/lookout/sdk/event.proto#L81 ?
Is there any other things to do other than droping from the `lookout-sdk` `.proto`, regenerate `lookout-sdk` code, and update code here in `looout` code?

**Comment by smacker** [comment]
yes. Currently, no analyzer uses this field.

So just removing it from proto, code generation and removing code that fills this field in lookout (a couple of lines) are everything that is needed.

**Comment by smola** [comment]
It sounds good if we are not using it and has no appropriate behavior. It would be good to check with @mcuadros since he conveived that part.

**Comment by mcuadros** [comment]
Up to you @smola
