### ISSUE TITLE
Refactor github provider to use pull requests api

### ISSUE THREAD

**Issue by smacker** [src-d/lookout#85]
I started digging into #77 and found out current /events API isn't suitable for us.

Example of the current state of lookout:
There is a pull request #81. It was re-pushed force after rebase on master. Now let's look at github responses:

Pull requests API:
https://api.github.com/repos/src-d/lookout/pulls
https://gist.github.com/smacker/6378f49c4c6108b50bae2e1041e3fa2f

`[0].head.sha = 'cd15e2c050763e2ac3d444521eb28d06c9f47326'`

Events API:
https://api.github.com/repos/src-d/lookout/events
https://gist.github.com/smacker/1c82e55e001f2e27efdfe0242b33bd9d

`[13].payload.pull_request.head.sha = 'dfa9b65007a3c737d682e561ae2f7a1741d81b2b'`

there is no push event to pull request branch or any other event that updates PR:
```
$ grep "cd15e2c050763e2ac3d444521eb28d06c9f47326" events.json  | wc -l
       0
```

So there is no way to get up-to-date sha for pull request using event api.

**Comment by bzz** [comment]
This is super-strange! 

Why do you think in this case there was no a https://developer.github.com/v3/activity/events/types/#pushevent that could be picked up from Event API as well?
